name: my_project
version: 1.0
config-version: 2

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target"]

models:
  my_project:
    sales_view:
      description: "View of sales orders with formatted order dates."
      columns:
        - name: order_id
          description: "Unique identifier for the order."
        - name: customer_id
          description: "Unique identifier for the customer."
        - name: formatted_order_date
          description: "Order date formatted as YYYY-MM-DD."
        - name: total_amount
          description: "Total amount of the order."
